### ISSUE TITLE
GLM not working on jamovi for Linux

### ISSUE THREAD

**Issue by SvenHeimbuch** [dustinfife/flexplot#1]
If I try to use GLM part of flexplot on Linux, it is not working. Plots and tables are showing the spinning wheel forever, but no progress is made.

I am using jamovi 1.1.15 on Linux with flexplot 0.1.0 installed via jamovi's library.

However, on a Windows VM everything is working fine.

**Comment by dustinfife** [comment]
hmmm...what kind of model are you trying to fit? Numeric predictor? Categorical? Both? And you've successfully plotted that same model in flexplot?

**Comment by SvenHeimbuch** [comment]
It doesn't really matter what variable type is used. Take the Big5 dataset for example and use any variable. On Linux it's not fitting anything, it's loading forever. On Windows, it works immediately.

Linux version:
![flexplot_linux](https://user-images.githubusercontent.com/27767378/66547207-04f2d180-eb3f-11e9-9971-34292122aef2.png)

Windows version:
![flexplot_windows](https://user-images.githubusercontent.com/27767378/66547208-04f2d180-eb3f-11e9-8d0c-432d7832f0ce.png)

**Comment by dustinfife** [comment]
Sorry, I was out of town for a couple of days. I'll dive a little deeper and see if I can figure out what's going on.

**Comment by dustinfife** [comment]
Okay...I revamped the flexplot module quite a bit. Do you know how to side load in jamovi? If not, here's a video showing you how: 

https://www.youtube.com/watch?v=S25AL1b_uE0&list=PL8F480DgtpW-0u2Syk3K7Jqn0kDZtKFiO&index=5&t=0s

The file to sideload is located here:
https://github.com/dustinfife/flexplot/blob/development/flexplot.jmo

Let me know how that works out.

**Comment by SvenHeimbuch** [comment]
Thanks for your efforts. But it got even worse...It's not even showing the spinning wheel anymore. It doesn't do anything, at least nothing visible. CPU load goes up to 100%, until the jamovi process terminates itself.

![Screenshot from 2019-10-23 16-14-05](https://user-images.githubusercontent.com/27767378/67401980-2bd5ec80-f5b0-11e9-9e80-c8a9329abc71.png)

Before I sideloaded your linked module, I cleanly uninstalled the previous version.

If I can do anything to debug, please let me know.

**Comment by dustinfife** [comment]
Sorry about that. I forgot to include some dependencies. I'm hoping that's the issue. I've merged the development and master branch, so go ahead and try reinstalling the flexplot.jmo file and let me know what happens.

**Comment by SvenHeimbuch** [comment]
Exactly the same as with the previous one. 100% load until the process terminates. I will try it on a different linux machine asap to rule out that my flatpak install might be corrupted.

**Comment by SvenHeimbuch** [comment]
FYI, I tried it on two other machines with different distros (Arch, Debian) and the result is always the same as above. I believe there is some package incompatibility, but I have no clue where to start.

**Comment by SvenHeimbuch** [comment]
Some more forensic info. I had to recompile and replace the following R packages: `dplyr`, `glue`, `tidyselect` and `purrr`, cause the versions you ship with the module threw me this error: `Error : package ‘dplyr’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version`.

But now I'm back at square one, the spinning wheel...

**Comment by dustinfife** [comment]
This is starting to sound like a jamovi issue. Let me check in with them and see if they have anything we can try.

**Comment by dustinfife** [comment]
Still no work from Jamovi yet. Have you tried using the R version of flexplot in linux?

**Comment by SvenHeimbuch** [comment]
The R package works perfectly fine. It's the jamovi one that bugs me. And I'd love to use that module for my students.

**Comment by dustinfife** [comment]
I had another person confirm the issue with linux, but I haven't heard from the jamovi developers. Because this is a jamovi issue, I'm going to close this. I'll update if they ever say anything.

Do you have many students using linux?

**Comment by SvenHeimbuch** [comment]
For the students themselves, it shouldn't be an issue. Most of them use Windows or Mac. But for me as teacher it is an issue when I want to live demo something. In case of emergency I'll use jamovi in a Windows VM. Not optimal, but should be sufficient until there's a solution.

**Comment by dustinfife** [comment]
Yeah, sorry about that. I'll hound the jamovi developers again and see if we can get this worked out.
