### ISSUE TITLE
scale() causes "differing number of rows" error by flexplot::visualize()

### ISSUE THREAD

**Issue by RickPack** [dustinfife/flexplot#105]
Feature enhancement consideration: Any use of the scale() function causes flexplot::visualize() to throw a "differing number of rows" error when flexplot::visualize() is called on a model object created based on that scaled data frame. This seems to be because scale() turns vectors into a [one-column matrix](https://stackoverflow.com/a/20016680/2305061).

Given how often I think scale() is used to standardize variables, the package documentation might note the need to use as.numeric on the scaled vector. I believe I could find time to this in the next couple weeks if desired.

### Reproducible example
This example ends with
**Error** in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 200, 400
```
require(flexplot)
require(dplyr)
data(exercise_data)
exercise_data <- exercise_data %>% 
  mutate(hi_weight_loss_category = case_when(
    weight.loss > 5 ~ 1,
    TRUE ~ 0))
exercise_data$hi_weight_loss_category <-
  as.factor(exercise_data$hi_weight_loss_category)

exercise_data_scaled <- exercise_data %>% 
  mutate(hi_weight_loss_category_c = as.character(hi_weight_loss_category)) %>% 
  mutate_if(is.numeric, function(x) {
    **## !!! error avoided by using
    ## as.numeric(scale(x, center = TRUE, scale = TRUE))}) %>%** 
    scale(x, center = TRUE, scale = TRUE)}) %>% 
  mutate(hi_weight_loss_category = 
           as.factor(as.numeric(hi_weight_loss_category_c))) %>% 
  dplyr::select(-hi_weight_loss_category_c)

glm1 <- glmer(
  formula = hi_weight_loss_category ~ 
    health + gender + (1|therapy.type),
  family = binomial,
  data = exercise_data_scaled
)

flexplot::visualize(glm1, plot = "residuals")

```

**Comment by dustinfife** [comment]
Thanks for bringing this to my attention. My [most recent commit](https://github.com/dustinfife/flexplot/commit/ea4cf4f7f42f5e438f7708965abeee4cf1c9fc0b) fixes this issue.
