### ISSUE TITLE
Error w/ Estimates 

### ISSUE THREAD

**Issue by goyals48** [dustinfife/flexplot#109]
Hi Dustin,

I have been having some issues w/ the estimate function when using both my data and the jedi data following your "Using Flexplot for Mixed Models" tutorial. 

when running a model such as: model = lmer(darkness~anger + emotional_bonds + (anger+emotional_bonds|dojo_id), data=d), I receive the following error:

> estimates(model)
Error in str2lang(x) : <text>:1:15: unexpected ')'
1: darkness~1+(1|)
                  ^ 

Thanks so much in advance for your help!

**Comment by schubertLe** [comment]
for me lme4::lmer instead of only lmer worked
