### ISSUE TITLE
Convert dependent variables to log-scale

### ISSUE THREAD

**Issue by archgen** [dustinfife/flexplot#111]
Hi @dustinfife just inquiring into the possibility / sensible way of transforming one of the dependent variables to log-scale within the flexplot functionality. 
Many thanks! 

E.G
y = runif(10, 0:1)
x = rnorm(10, 5000:100000)
z = c(rep("y", 5), rep("n", 5))
d = data.table("y" = y, "x" = x, "z" = z)

flexplot(y~x, d)
flexplot(y~x+z, d)

Then doing something like you would in ggplot
flexplot(y~log10(x), d)
flexplot(y~log10(x)+z, d)

**Comment by dustinfife** [comment]
I think you can with a IV, but not the DV. You could always do something like this:

```
flexplot(y~x, data=d %>% mutate(y = log(y, base=10))
```
