### ISSUE TITLE
Simple slope plans

### ISSUE THREAD

**Issue by doctorzimmy** [dustinfife/flexplot#112]
This isn't an issue in the way that an issue means there is a problem, but more of a suggestion to make flexplot even more awesome. 

In OLS regression, when there is a significant interaction and we dig into the nature of that interaction via simple slopes, I was hoping that some sort of simple slope analysis can be added to flexplot. Kris Preacher has this tool: https://quantpsy.org/interact/hlm3 but holy cow! I'm still wrapping my mind around R an R studio (long time SAS user, first time R user) and HLM models (I was more focused on passing comps than mastering HLM regression) in general and trying to use this tool to dig into my interaction is making my brain turn into jelly. I'll keep at it but it sure would be easier to type something like:

**simple.slopes("insert model here", whatever options are needed, data=d)**

and let R do the rest of the heavy lifting.

**Comment by dustinfife** [comment]
[I've written elsewhere](https://quantpsych.net/simple-slopes-models-in-jasp-r/) that I'm not a big fan of simple slopes analyses. I think how flexplot handles interactions is better.
