### ISSUE TITLE
using flexplot for lmer

### ISSUE THREAD

**Issue by Jacsbill** [dustinfife/flexplot#116]
Firstly, thank you for creation of this package!

I'm having slight trouble with running your example on page 492  of your Psychological Methods (2022) paper. 

`library(flexplot)
require(lme4)
data(math)
model = lmer(MathAch ~ Sex + SES +(SES|School), data = math)
visualize(model, plot="model", formula = MathAch ~ SES + School|Sex, sample =3)`

Error

`Error in model$model : $ operator not defined for this S4 class`

I'm fairly new to R and running lmer so apologise if this is an easy fix, but just checking it isn't a bug. I updated R yesterday and have had a few issues with code since then.  I've tried variations of using as.function but to no avail. 

R Studio version 2023.03.0 Build 386

Also, should flexplot with glmer models? 

Thank you. JB

**Comment by dustinfife** [comment]
Do you happen to have lmerTest loaded as well? If so, it replaces lmer and causes problems with flexplot.

**Comment by dustinfife** [comment]
If that is the problem (and I think it is), this should be fixed with the most recent commit. Reinstall flexplot and it should work.

**Comment by Jacsbill** [comment]
I detached lmerTest and it works. Will reinstall flexplot. Thank you for such a speedy reply.
