### ISSUE TITLE
method = logistic using categorical variable

### ISSUE THREAD

**Issue by kgkirgkiris** [dustinfife/flexplot#138]
Hi,

When I use the following simple algorithm, as I am experimenting with flexplot for the first time, it seems that on the y axis "yes" appears where "no" was supposed to appear, and vice versa. In data "avengers" the observations that died="yes" were substantially lower than "no". However, in the plot the value of "died" that correspond to "yes" is named as "no" and vice versa.
Is this due to problematic use of categorical variables by the model? If yes, how to prevent this from happening?

Thank you in advance.

flexplot(died~willpower | minutes.fighting, data=avengers, 
         method = "logistic", ghost.line="gray")

**Comment by dustinfife** [comment]
Good catch. Let me see if I can fix that.

**Comment by dustinfife** [comment]
Okay, I think it's fixed now. Unfortunately, R defaults to putting "No" at the top of the Y axis instead of "Yes," but you can convert it to an ordered factor:

`
flexplot(died~willpower | minutes.fighting, 
         data=avengers %>% mutate(died = factor(died, levels=c("no", "yes"), ordered=T)),
         method = "logistic", ghost.line="gray")
`
