### ISSUE TITLE
Sorting factors?

### ISSUE THREAD

**Issue by Losses** [dustinfife/flexplot#23]
The x-axis looks really weird...
![image](https://user-images.githubusercontent.com/1384036/67821797-3dac1800-faf9-11e9-8630-698770b5f297.png)

**Comment by dustinfife** [comment]
flexplot defaults to ordering the axis by the size of the medians. You can change it by modifying the variable type in Jamovi. Go to data -> set up -> then set up the variable as ordinal and specify the levels (in your case 1a, 1b, 2a, 2b, etc.
