### ISSUE TITLE
Added added.plot capability to compare.fits?

### ISSUE THREAD

**Issue by emmamcb948** [dustinfife/flexplot#26]

**Comment by dustinfife** [comment]
I thought a little more about this and I don't think it makes sense. Say you want to compare.fits with y ~ a + b versus y ~ a * b. The avp will residualize the effect of a. So now you're going to plot the residuals against b for the first model. But what does the  second model plot? You're removing the effect of a, which is part of the interaction term...so I'm not sure it make sense to do.
