### ISSUE TITLE
Issue with model.comparison for logistic regression

### ISSUE THREAD

**Issue by emmamcb948** [dustinfife/flexplot#28]
mod.reduced = glm(major.dep~distress, data = d, family = binomial)
mod.full = glm(major.dep~distress + sex, data = d, family = binomial)
compare.fits(major.dep~distress|sex, data = d, method = "logistic", jitter = c(0, 0.1),
             mod.reduced, mod.full)
model.comparison(mod.full, mod.reduced)

**> model.comparison(mod.full, mod.reduced)
Error in model.comparison(mod.full, mod.reduced) : 
  object 'mod1' not found**

**Comment by dustinfife** [comment]
Fixed!
