### ISSUE TITLE
visualize not working for categorical predictor

### ISSUE THREAD

**Issue by TKane9** [dustinfife/flexplot#30]
d = relationship_satisfaction %>%
 select(satisfaction, gender) %>%
 filter(gender!="Mantis religiosa")
 mod = lm(satisfaction~separated, data=relationship_satisfaction) 
 flexplot::visualize(mod) 
 estimates(mod) 

Note: one or more of your variables has less than 5 values, yet they're treated as numeric.

Error in parse(text = x, keep.source = FALSE) : 
  <text>:1:14: unexpected '|'
1: satisfaction~|
                 ^

**Comment by dustinfife** [comment]
It doesn't seem to be an issue now. Not sure what I did, but I'm sure it was brilliant.
