### ISSUE TITLE
Unable to view help file for vizualize.lmerMod

### ISSUE THREAD

**Issue by TarandeepKang** [dustinfife/flexplot#38]
Dear Prof Fife,

When I browse the help file contents in R Studio, for guidance on visualising mixed models, I received the following error message:

Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/flexplot/help/flexplot.rdb' is corrupt

Thanks in advance for any help you are able to provide.

Kind regards,

Tarandeep Kang

**Comment by dustinfife** [comment]
Do you mind pasting the code you're using?

On my end, this works:

`?visualize.lmerMod `

**Comment by TarandeepKang** [comment]
I've tried bothManually searching theHelp files using the help viewer in RStudio And the same code you use above; both produced this error message.

**Comment by dustinfife** [comment]
Ok. Can you tell me your operating system, version of Rstudio, and version of flexplot?

Thanks!

**Comment by TarandeepKang** [comment]
I Just updated RStudio, nd everything works perfectly now! Sorry for the unnecessary hassle (We British people really must apologise for everything!) I will close this now.
