### ISSUE TITLE
Flexplot error when using read_sav from haven  

### ISSUE THREAD

**Issue by traver22** [dustinfife/flexplot#44]
Whenever a categorical variable is read in through read_sav, it tries to retain SPSS labels. This messes up flexplot.

**Comment by dustinfife** [comment]
This is actually not an error, but a warning. It seems that if a categorical variable is read in from SPSS, the haven package will convert it to a format flexplot doesn't understand. It defaults to treating it as numeric, which is reasonable. If you want to prevent it from doing so, just use `as_factor` from the haven package.
