### ISSUE TITLE
error <text>:1:1: unexpected '<' 1: < ^

### ISSUE THREAD

**Issue by devinyak** [dustinfife/flexplot#45]
Dear Dustin!
I'he got errors while trying flexplot with Jamovi 1.2. The error is thrown just after the selection of any column into outcome or predictor panel. I am using Windows 10 with ukrainian locale if this is an issue.

Here is the output:
Debug

Error in parse(text = x, keep.source = FALSE): <text>:1:1: unexpected '<'
1: <
    ^

private$.run()
as.formula(formula)
formula(object, env = baseenv())
formula.character(object, env = baseenv())
formula(eval(parse(text = x, keep.source = FALSE)[[1]]))
eval(parse(text = x, keep.source = FALSE)[[1]])
parse(text = x, keep.source = FALSE)

**Comment by dustinfife** [comment]
I'm not able to replicate that error. Are you in flexplot or general linear model? Can you send me a screenshot?

**Comment by devinyak** [comment]
Sorry for troubling, I've found the source. That was due to cyrillic column names. Seems that the library does not support cyrillic somewhere in the source code. All works fine with latin alphabet.

**Comment by dustinfife** [comment]
Gotcha. Thanks!
