### ISSUE TITLE
repo="development" error

### ISSUE THREAD

**Issue by BobMuenchen** [dustinfife/flexplot#47]
I copied this directly off the flexplot page:

> devtools::install_github("dustinfife/flexplot", repo="development")
Error in parse_repo_spec(repo) : 
  Invalid git repo specification: 'development'

The other install_github command there worked fine.

**Comment by dustinfife** [comment]
Oops! That was a type. It should say:

```
devtools::install_github("dustinfife/flexplot", ref="development")
```
