### ISSUE TITLE
invalid data

### ISSUE THREAD

**Issue by alexgrote** [dustinfife/flexplot#51]
Dear Dustin,
I am new to this. Until now I have used JMP to do my basic statistics. Actually I try to switch to jamovi. I got some very nice results with your flexplot extension, but not always. I have some problems, which are probably "user related" as I am a "no-math" person..... 
I understood the outcome field like I could use nominal or continuous data. And there I got different failure notes. Saying "unexpected symbols" or "unexpected numeric term"
![unexpected numeric absolut term](https://user-images.githubusercontent.com/64128825/79956807-eb80f980-8480-11ea-9419-9c36c540d4a8.jpg)
![unexpected symbol](https://user-images.githubusercontent.com/64128825/79956819-f0de4400-8480-11ea-85fa-414cd41beca7.jpg)

Can you give my some advice?
Thanks a lot 
alex

**Comment by dustinfife** [comment]
Hi Alex. Thanks for sending that. My guess is that flexplot doesn't want spaces in the variable names. Have you tried the same analysis with variables that don't have spaces? Try that and let me know if you have any issues. If it is the spaces, I'll see about modifying flexplot so it can have spaces in variable names.

**Comment by alexgrote** [comment]
Hi Dustin,
the problem seems to be only in the naming of the columns. After deleting all blank spaces and "-" it woks perfectly. Thanks a lot for your immediate response.
Cheers alex
