### ISSUE TITLE
Can't install flexplot package in R

### ISSUE THREAD

**Issue by TomerKar** [dustinfife/flexplot#60]
Hi, I tried reaching the R package flexplot and got the following error message (screenshot attached):
![dfgdhdxfhjfjdgfjdfgh](https://user-images.githubusercontent.com/71724659/93918976-ca655300-fd15-11ea-96d8-9174e1bcc0fb.png)

Couldn't find flexplot when I searched for it via RStudio either.

Thanks,
Tomer

**Comment by dustinfife** [comment]
Try doing this:

`devtools::install_github("dustinfife/flexplot", ref="development")`

**Comment by TomerKar** [comment]
Thanks again Dustin for all your help.
Got a different error this time... :(
I don't want to steal any more of your time though.
Really appreciate all your trouble, you're great.

Have a nice one,

Tomer

**Comment by dustinfife** [comment]
You're not stealing my time. I have a vested interest in Flexplot working. Can you share the error message?

Thanks!

**Comment by TomerKar** [comment]
Hi Dustin,

Tried it again to copy the error message and it worked.
I now have flexplot, yay!

Thanks a lot,

Tomer

**Comment by dustinfife** [comment]
Happy to hear!

**Comment by yukokino** [comment]
Hi, I would love to try flexplot. I tried 

devtools::install_github("dustinfife/flexplot", ref="development") 

but I still cannot install it. I am using R 4.0.0. Would you be able to suggest any other thing to try? I got a very long error message, so I attached it as a text file.
[flexplot installation error message.txt](https://github.com/dustinfife/flexplot/files/8932946/flexplot.installation.error.message.txt)

**Comment by charliejk** [comment]
I think that R 4.0.0 is already an order version of R thus it is not suitable for installation of the development version of flexplot.

**Comment by AnilYasin** [comment]
Try to re-install devtools. In my case, it solved the problem. I hope this helps.

**Comment by lisakaly** [comment]
I did loaded flexplot and lme4 to run a linear mixed model on r. But what ever my model is ,with or without interaction, the error answer is the same:
Error in if (preds[i] != term.re) { : argument is of length zero
Calls: <Anonymous> ... visualize -> visualize.lmerMod -> make_formula_mixed
I tried also with mixed.mod.visual , still an error message. 
This is the reference of my R:
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

If you could help to solve it it anyways?

**Comment by NateLaS** [comment]
Is this a firewall issue? It's happened with other packages as well :(

```
> devtools::install_github("dustinfife/flexplot", ref="development")
Downloading GitHub repo dustinfife/flexplot@development
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/dustinfife/flexplot/tarball/development'
```

**Comment by dustinfife** [comment]
It could be.

**Comment by NateLaS** [comment]
Ah, damit. Anything I could try?
