### ISSUE TITLE
"Unexpected end of input message" error when DV is inserted 

### ISSUE THREAD

**Issue by claudiodang** [dustinfife/flexplot#66]
Hi Dustin, I just discovered your tool and it's amazing! 

1. It worked very well in the beginning but then I wanted to import my DV "Income" and I got the error message "unexpected end of input in "Income" 2". I didn't screenshot it because it went away after removing the Flexplot I was working on and starting a new one. But I thought I'd let you know. 

2. Do you have any recommendation to visualise my multiple regression model to predict "Income" with 4 independent variables being "GPA", "Department"(8 levels), "GraduateYear"(4 levels) and "CostofLiving in the participant's country"? 
I have tried multiple ways but it always looks very messy.

Thank you so much!
Kind regards from Germany

**Comment by dustinfife** [comment]
Hi!

See below. 

> It worked very well in the beginning but then I wanted to import my DV "Income" and I got the error message "unexpected end of input in "Income" 2". I didn't screenshot it because it went away after removing the Flexplot I was working on and starting a new one. But I thought I'd let you know.

It's hard to say without a screenshot. What version were you using? Are you using R? Or JASP? Or Jamovi? A bit more info would be helpful

> Do you have any recommendation to visualise my multiple regression model to predict "Income" with 4 independent variables being "GPA", "Department"(8 levels), "GraduateYear"(4 levels) and "CostofLiving in the participant's country"?
I have tried multiple ways but it always looks very messy.

It is hard to visualize four at a time. Do you really need to see all of them? A few suggestions:

1. Get rid of variables that don't contribute anything, if you can. 
2. See if there's any evidence of interactions/nonlinear effects. If there are none, you can just use added variable plots for each variable, one at a time.

**Comment by claudiodang** [comment]
Hi, I was using the newest version of Jamovi

Thank you for your suggestions
