### ISSUE TITLE
Error message when Installing

### ISSUE THREAD

**Issue by MaggieDee** [dustinfife/flexplot#67]
Hello, I wanted to use flexplot and I tried using both development and stable commands to install it but I continue to get the following error message:

Error: Failed to install 'flexplot' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

is there any other way I can install this package?

Thank you!

**Comment by dustinfife** [comment]
Sorry! This message slipped my attention. Try installing rlang, then try installing flexplot again.
