### ISSUE TITLE
Clusters argument has a problem with visualize function

### ISSUE THREAD

**Issue by dustinfife** [dustinfife/flexplot#70]
From a YouTube comment: 

The command "visualize(baseline, clusters=3)" generates: Error in compare.fits(formula, data = k, model1 = object, model2 = object,  : 
  formal argument "clusters" matched by multiple actual arguments. My baseline is a result of lmer function (i.e. baseline=lmer(data=data.it, y~1+(1|subject)). The visualize function produced same error for various values of cluster. When I omit the cluster, I get the graphic

**Comment by hcslppl** [comment]
Hey Dustin, I've been trying to plot the baseline model using flexplot::visualize and keep getting this error:
Error in if (preds[i] != term.re) { : argument is of length zero

The model and ICC run fine, I just cant get visualize to work.

**Comment by dustinfife** [comment]
Have you tried updating to the development version? try:
`
devtools::install_github("dustinfife/flexplot", ref="development")`
