### ISSUE TITLE
Unable to download/install flexplot

### ISSUE THREAD

**Issue by nadav-pezaro** [dustinfife/flexplot#72]
Hi, I am having trouble downloading flexplot. I have tried both of these codes:
devtools::install_github("dustinfife/flexplot", ref="development")
devtools::install_github("dustinfife/flexplot")
The error messages (screen grab attached) are the same for both and basically say that the download failed.  

"Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/dustinfife/flexplot/tarball/HEAD' failed"

Any ideas?
Thank you
[Screen grab _ flxplot download.pdf](https://github.com/dustinfife/flexplot/files/6589684/Screen.grab._.flxplot.download.pdf)

**Comment by dustinfife** [comment]
It looks like that's a devtools error. See [this stackexchange answer](https://stackoverflow.com/questions/65421798/devtoolsinstall-github-failing-in-r4-0-03). I'd suggest you try the following:

```
options(timeout=9999999)
install_github("dustinfife/flexplot")
```

**Comment by nadav-pezaro** [comment]
Sorted! Thank you!
