### ISSUE TITLE
ghost.reference in flexplot

### ISSUE THREAD

**Issue by charliejk** [dustinfife/flexplot#88]
Hi,
I am trying to tell flexplot which ghost line I want, however I get one of two issues (depending on the number of independent variables I put and type of variable).

1. Error in cut.default(as.numeric(data[[variable]]), breaks, labels = labels,  : 
  'breaks' are not unique
2. Error in Ops.factor((k[, binned.name]), unlist(ghost.reference[[given[s]]])) : 
  level sets of factors are different

Error 1 happens when I set parameters as factors (however, they are integer 0 or 1). Error 2 happens when the parameters are factors. I don't know what I'm doing wrong.

**Comment by dustinfife** [comment]
Can you show me the code you're using when you get these errors?

**Comment by charliejk** [comment]
> Can you show me the code you're using when you get these errors?
Here, I will try to explain my data and line of code for the the second error (i.e. with Ops.factor). I am not sure at this point what caused the first error.

I use in R ver. 4.0.4, and the code that make the problem is:
`flexplot( min.count ~ kstep + LocalSearch | kmax + SearchDirection , data=d.a.new, bins=7, ghost.reference=list(LocalSearch=1, kmax=10, SearchDirection=1), ghost.line="red")`

The same line of code works when I omit ghost.reference. My data is in the data.frame variable called d.a.new.
>head(d.a.new)
    kmax kstep plato SearchDirection LocalSearch min.count KMINcode
1    1       1      0.0               0                      0                61        0
2    1       1      0.1               0                      0                57        0
3    1       1      0.5               0                      0                52        0
4    1       1      0.9               0                      0                48        0
5    1       1      1.0               0                      0                55        0
6    2       1      0.0               0                      0                69        0
All columns have integer or numeric values. 
p.s. Sorry for such late reply.

**Comment by dustinfife** [comment]
Do you really need 7 bins? I suspect that may be part of the issue. 

Also try omitting LocalSearch=1?

**Comment by charliejk** [comment]
I need 10 bins, but it seems that flexplot has set 7 as the maximum. In any case,  I get the same error when I don't use the option for bins. Similarly, the same error occurs if I don't set LocalSearch in ghost.reference. Consequently, the error happens for:

`flexplot( min.count ~ kstep + LocalSearch | kmax + SearchDirection , data=d.a.new, ghost.reference=list(kmax=10, SearchDirection=1), ghost.line="red")`

I tried with different values for kmax (which is any integer [1,10]), and for SearchDirection being 0. The error repeats.

**Comment by charliejk** [comment]
Please find my input find attached here.

[agg_clean-ogra50_50-vns_swap-plotfull_kmin--kminrand--kminrand2--kminrand3.ogra50.p4.100puta200ITmax.txt](https://github.com/dustinfife/flexplot/files/8268530/agg_clean-ogra50_50-vns_swap-plotfull_kmin--kminrand--kminrand2--kminrand3.ogra50.p4.100puta200ITmax.txt)

**Comment by dustinfife** [comment]
This should be fixed with the most recent commit on the development branch. 

You might want to look into specifying the breaks for each variable individually, something like:

```
flexplot( min.count ~ kstep + LocalSearch | kmax  + SearchDirection, 
          data=d, 
          ghost.reference=list(kmax=10, SearchDirection=1), 
          breaks = list(kmax = c(1,3,5,7)),
          ghost.line="red")
```
