### ISSUE TITLE
Compare.fits provides visualizations for the same model

### ISSUE THREAD

**Issue by reecetan7** [dustinfife/flexplot#91]
Hi Dustin,

I'm trying to visualize my random slopes model using compare.fits function in flexplot and I had a question I wanted to run by you. When I ran the compare.fits function with just one model entered, I saw what looked like the same line across all of the clusters presented (see red m1 in the graphic). After a little bit of tinkering, I found that if I included the same exact model (just named differently) I get a different prediction (see blue m2 in the graphic). The visualization of m2 is more what I expected to see when building the random slopes model, but I'm not sure if what's presented in m1 is something I should be concerned with. I've tried reading up on the compare.fits function, and I thought I could just use it for visualizing one model, but do I have to put 2 to obtain the correct visualization? Could you maybe let me know what is being plotted in m1 and why is it different than m2? Thanks and let me know if I can get you any additional information. Please see the attached graphic, data frame and R script below. 

Best,
Tanner

![Flexplot question](https://user-images.githubusercontent.com/101607965/164055021-ee2af0a2-91ec-471a-bf82-8ce2c022eb05.png)

[MU Multilevel Modeling.csv](https://github.com/dustinfife/flexplot/files/8514925/MU.Multilevel.Modeling.csv)

##########
rm(list=ls())
library(flexplot)
library(lme4)

setwd("/Users/Tanner/Desktop/Tanner Reece BFR RT 2021")
MU_data <- read.csv("MU Multilevel Modeling.csv")
MU_data$time <- factor(MU_data$time, levels=c("Pre","Post"))
MU_data$time <- relevel(MU_data$time, "Pre")

MU_data$RT_bin <-cut(MU_data$RT, breaks=c(-1, 10, 20, 30, 40, 50, 60, 77))

m1 <- lme4::lmer(MUAP ~ time + (time|Subject.ID), data = filter(MU_data, group == "BFR" & RT_bin == "(20,30]"), REML=FALSE)
m2 <- lme4::lmer(MUAP ~ time + (time|Subject.ID), data = filter(MU_data, group == "BFR" & RT_bin == "(20,30]"), REML=FALSE)

compare.fits(MUAP~time | Subject.ID, data = filter(MU_data, group == "BFR" & RT_bin == "(20,30]"), model1=m1, model2=m2, clusters = 10)
#########

**Comment by dustinfife** [comment]
Sorry for the very delayed response. It looks like the first model is plotting the fixed effects and the other is plotting the random effects. That's not what it should be doing, but unfortunately it is. I'll look into why this might be.

**Comment by reecetan7** [comment]
No worries! Thanks for following up. Please do and let me know if you need any other information from me!

**Comment by dustinfife** [comment]
This should be fixed with the most recent commit for the development branch. Install flexplot again and it should work:

`devtools::install_github("dustinfife/flexplot", ref="development")`
