### ISSUE TITLE
Cannot install flexplot in R

### ISSUE THREAD

**Issue by Starry-eye** [dustinfife/flexplot#94]
Hi, thanks for the great explanations on youtube
I tried to install flexplot but these error came in may way.
<img width="906" alt="image" src="https://user-images.githubusercontent.com/106257724/170288532-38eaf50f-f511-4d60-8c1d-c5161aebfe4e.png">
<img width="910" alt="image" src="https://user-images.githubusercontent.com/106257724/170288655-0bd0faf9-be49-4a03-a190-e86edf294932.png">
<img width="909" alt="image" src="https://user-images.githubusercontent.com/106257724/170288801-3da3dcb5-1c39-4ed8-9b4d-18e3fac85d35.png">
<img width="906" alt="image" src="https://user-images.githubusercontent.com/106257724/170288892-d35f61c6-7069-4039-b2d5-09e15dd7932e.png">

I tried to install packages mentioned in the error but similar messages always show up
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/106257724/170289122-76c1c7c0-a75d-45c1-950d-1690a2c8d317.png">

Would you please help me finding what's wrong?
my R version is 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for macOS. Thank you so much for your help!

**Comment by dustinfife** [comment]
Are you using R 3.6? It's probably failing because of that. I'd update R and try again.
