### ISSUE TITLE
Unable to download flexplot in R

### ISSUE THREAD

**Issue by Iamquitesmart** [dustinfife/flexplot#96]
Dear Dustin:

I tried to use flexplot to run some glm, but I am unable to download flexplot. My error message is:

devtools::install_github("dustinfife/flexplot", ref="development")
Downloading GitHub repo dustinfife/flexplot@development
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/dustinfife/flexplot/tarball/development' failed

![image](https://user-images.githubusercontent.com/58895061/172651882-0c1bb84d-6430-42a2-9258-8dd93553c9e4.png)

I am using R version 4.2.0

Can you let me know how can I resolve this? Many thanks!

**Comment by tevinown** [comment]
I have the same question........
> devtools::install_github("dustinfife/flexplot")
Downloading GitHub repo dustinfife/flexplot@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/dustinfife/flexplot/tarball/HEAD' failed


how can I resolve this? Many thanks!

**Comment by menage95** [comment]
I have also had this error and would like to know how to fix! 

thanks

**Comment by dustinfife** [comment]
I'm not exactly sure why this is. I assume you're connected to the internet?

You could also try downloading from the development branch:

`devtools::install_github("dustinfife/flexplot", ref="development")`
