### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Bernardsj** [dustinfife/flexplot#98]
Hello, 

I am trying to install the flexplot package and receiving a very vague message: 

devtools::install_github("dustinfife/flexplot", ref = "development")
Downloading GitHub repo dustinfife/flexplot@development
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/dustinfife/flexplot/tarball/development' failed

I am running R 4.2.1 and have tried both the master and dev versions. 

The only way I can install the package is to download the zip and install it locally via devtools::install_local().

Not sure if this is on my end, however,  I can download other packages via devtools::github_install()

**Comment by dustinfife** [comment]
Are you using a VPN? It could be a firewall issue. 

There's another option I saw. Try this:

```
options(timeout=9999999)
install_github("dustinfife/flexplot", ref="development")
```
